//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.Android.Maps.Utils")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-returntypes.15+Branch.returntypes.Sha.75e5b1d134584516f497cfa4097839d4eea09a03")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

